export type LearnCategory =
  | "Getting Started"
  | "Money & Profit"
  | "Sales"
  | "Expenses"
  | "Accounting"
  | "GST"
  | "Company Ownership"
  | "Developer";

export type LearnConcept = {
  id: string;
  simpleName: string;
  accountingName: string;
  category: LearnCategory;
  simple: string;
  advanced: string;
  why: string;
  aliases: string[];
  caution?: string;
};

export const LEARN_CONCEPTS: LearnConcept[] = [
  {
    id: "revenue",
    simpleName: "Revenue",
    accountingName: "Revenue",
    category: "Money & Profit",
    simple: "Money your business earns from selling products or services, before subtracting expenses.",
    advanced: "Revenue is credited when a sale is issued. It is not cash, and it is not profit. GST collected on top is not revenue.",
    why: "A busy month can still lose money if spending is higher than sales.",
    aliases: ["sales", "income", "earned", "turnover"],
  },
  {
    id: "expense",
    simpleName: "Expense",
    accountingName: "Expense",
    category: "Expenses",
    simple: "Money the business spends to operate, such as software, salary, rent, marketing, or travel.",
    advanced: "An expense reduces profit. Paying back the principal of a loan, or moving money between your own accounts, is not an operating expense.",
    why: "Profit only falls when the spend is a cost of running the business.",
    aliases: ["spend", "cost", "money out", "bills i paid"],
  },
  {
    id: "paid-personally",
    simpleName: "Paid personally",
    accountingName: "Reimbursement liability",
    category: "Expenses",
    simple: "You used your own money for a business expense, so the business owes you that amount. This does not change your ownership.",
    advanced: "The expense is debited and Due to team members is credited. Company cash, revenue, and shares stay unchanged. Each person is owed what they paid, not an equal split.",
    why: "A founder covering a domain or AWS bill is not the same as investing capital or earning shares.",
    aliases: ["paid personally", "i paid", "out of pocket", "founder expense"],
  },
  {
    id: "reimbursement",
    simpleName: "Reimbursement",
    accountingName: "Reimbursement payment",
    category: "Expenses",
    simple: "Reimbursement returns money you previously spent for the business. It is not a second business expense.",
    advanced: "Paying it back debits Due to team members and credits bank. The original expense stays. A partial payment leaves the rest due.",
    why: "Returning ₹1,200 does not mean the business spent ₹1,200 again.",
    aliases: ["reimburse", "pay me back", "money owed to team"],
  },
  {
    id: "retained",
    simpleName: "Profit kept in the business",
    accountingName: "Retained earnings",
    category: "Money & Profit",
    simple: "Business profit does not automatically belong in each founder's personal account. If it is not taken out, it stays in the business.",
    advanced: "Kharcha does not split leftover cash, pay founders, or issue dividends on its own. Retained earnings is the accounting name for profit that stays.",
    why: "Leaving money in the company is the default for a bootstrapped business.",
    caution: "This is not tax or legal advice about dividends.",
    aliases: ["retained earnings", "keep profit", "don't split profit"],
  },
  {
    id: "profit",
    simpleName: "Profit",
    accountingName: "Net profit",
    category: "Money & Profit",
    simple: "What is left after subtracting business costs from what you earned.",
    advanced: "Net profit is revenue minus cost of sales, operating costs, interest, and tax. It is not the cash in the bank.",
    why: "This is the number that says whether the business made money in the period.",
    aliases: ["monthly loss", "losing money", "made money", "bottom line"],
  },
  {
    id: "gross-profit",
    simpleName: "Gross profit",
    accountingName: "Gross profit",
    category: "Money & Profit",
    simple: "Sales minus the direct cost of those sales.",
    advanced: "Gross profit = revenue − cost of goods sold. Operating costs like rent come after this.",
    why: "It shows whether the thing you sell costs less than the price.",
    aliases: ["margin", "cost of sales"],
  },
  {
    id: "ebitda",
    simpleName: "Operating profit",
    accountingName: "EBITDA",
    category: "Money & Profit",
    simple: "How the core business is doing before interest, tax, and wear-and-tear costs.",
    advanced: "EBITDA means earnings before interest, taxes, depreciation, and amortization. Kharcha calculates revenue minus cost of sales minus operating expenses, and stops before those items.",
    why: "It helps you see the operation itself, separate from loans and non-cash costs.",
    aliases: ["ebitda", "operating profit"],
  },
  {
    id: "net-profit",
    simpleName: "Net profit",
    accountingName: "Net profit",
    category: "Money & Profit",
    simple: "What remains after business expenses, interest, and taxes.",
    advanced: "Net profit = operating profit − depreciation − interest − tax, in the way Kharcha classifies those accounts.",
    why: "This is the full period result, still not the same as cash.",
    aliases: ["net income", "profit after tax"],
  },
  {
    id: "cash",
    simpleName: "Cash available",
    accountingName: "Cash and bank",
    category: "Getting Started",
    simple: "Money currently sitting in the business cash and bank accounts.",
    advanced: "Cash is a point-in-time balance. Profit is a result over a period. An unpaid invoice can raise profit without raising cash.",
    why: "You can be profitable and still be unable to pay a bill.",
    aliases: ["bank balance", "money in hand"],
  },
  {
    id: "cash-flow",
    simpleName: "Cash flow",
    accountingName: "Statement of cash flows",
    category: "Accounting",
    simple: "Where actual money came from and where it went.",
    advanced: "Operating is normal business movement. Investing is buying or selling long-term assets. Financing is money from owners, investors, or loans.",
    why: "Profit does not tell you whether cash arrived.",
    aliases: ["where did the money go", "cash movement"],
  },
  {
    id: "receivable",
    simpleName: "Money to collect",
    accountingName: "Accounts receivable",
    category: "Sales",
    simple: "Money customers still owe your business.",
    advanced: "Issuing an invoice debits receivable and credits revenue (and GST payable). Collecting cash debits bank and credits receivable. Revenue is not recorded again.",
    why: "A sale can be real before the customer pays.",
    aliases: ["customer owes me", "customer owes", "owes me money", "unpaid invoice", "money to collect"],
  },
  {
    id: "payable",
    simpleName: "Money to pay",
    accountingName: "Accounts payable",
    category: "Expenses",
    simple: "Money your business owes to vendors or suppliers.",
    advanced: "A bill you have not paid yet is a liability. Kharcha only shows this when a payable has actually been recorded. It does not invent vendor bills.",
    why: "Spending you have agreed to can exist before cash leaves.",
    aliases: ["bills i owe", "vendors", "accounts payable"],
  },
  {
    id: "asset",
    simpleName: "What you own",
    accountingName: "Asset",
    category: "Accounting",
    simple: "Something the business owns that has value, such as cash, money customers owe, or equipment.",
    advanced: "Assets are the left side of the balance sheet. Cash, receivables, and equipment are assets.",
    why: "Owning something is not the same as having earned it.",
    aliases: ["assets", "equipment", "what we own"],
  },
  {
    id: "liability",
    simpleName: "What you owe",
    accountingName: "Liability",
    category: "Accounting",
    simple: "Money the business has to pay later, such as bills, loans, or tax collected.",
    advanced: "Liabilities are claims on the business by outsiders. GST collected and not yet paid sits here, not in revenue.",
    why: "A full bank account can still include money that is not yours, such as tax.",
    aliases: ["liabilities", "loan", "debt", "what we owe"],
  },
  {
    id: "equity",
    simpleName: "Owner's stake",
    accountingName: "Equity",
    category: "Company Ownership",
    simple: "What belongs to the owners after subtracting what the business owes.",
    advanced: "Assets = liabilities + equity. Owner funding increases equity. It is not revenue.",
    why: "This is the owners' claim, not a measure of this month's sales.",
    aliases: ["capital", "owner capital", "net worth"],
  },
  {
    id: "capital",
    simpleName: "Money you put in",
    accountingName: "Owner capital",
    category: "Getting Started",
    simple: "Money an owner puts into the business. The business did not earn it from a customer.",
    advanced: "Kharcha debits cash or bank and credits owner capital, retained earnings, or a loan, depending on where you said the money came from. Revenue stays unchanged.",
    why: "Starting money would fake a profit if it were treated as a sale.",
    aliases: ["opening capital", "investment by me", "starting balance"],
  },
  {
    id: "invoice",
    simpleName: "Invoice",
    accountingName: "Sales invoice",
    category: "Sales",
    simple: "A request for a customer to pay you. A draft does not change the books. Issuing it records the sale and the amount they owe.",
    advanced: "Draft: no journal. Issued: revenue and receivable (plus GST payable). Payment: bank up, receivable down. Revenue is not posted again.",
    why: "Deleting an issued invoice would hide a record the books already used.",
    aliases: ["bill the customer", "invoice lifecycle"],
  },
  {
    id: "credit-note",
    simpleName: "Credit note",
    accountingName: "Credit note",
    category: "Sales",
    simple: "A document that reduces an invoice you already issued, without erasing the original.",
    advanced: "Kharcha posts a reversing journal for the taxable amount and the GST. The original invoice stays in the history.",
    why: "Correcting a sale should leave a trail.",
    aliases: ["refund note", "cancel invoice", "reverse invoice"],
  },
  {
    id: "gst",
    simpleName: "GST",
    accountingName: "Goods and Services Tax",
    category: "GST",
    simple: "Tax you add on a sale. The tax itself is not your revenue. The customer pays it, and it is tracked as tax to pay.",
    advanced: "On an issued invoice, taxable value credits revenue. CGST, SGST, or IGST credits a tax payable account. Treatment depends on the seller state and the place of supply.",
    why: "Counting GST as income overstates profit.",
    caution: "This is how Kharcha records GST. It is not tax advice, and Kharcha does not file returns.",
    aliases: ["tax", "gst"],
  },
  {
    id: "cgst",
    simpleName: "CGST and SGST",
    accountingName: "CGST + SGST",
    category: "GST",
    simple: "The two halves of GST when the sale stays inside the same state.",
    advanced: "Kharcha splits the rate in half between CGST payable and SGST payable when the seller state and place of supply match.",
    why: "The split is a reporting detail. Neither half is revenue.",
    caution: "Treatment can vary. This describes Kharcha's model only.",
    aliases: ["cgst", "sgst", "same state"],
  },
  {
    id: "igst",
    simpleName: "IGST",
    accountingName: "IGST",
    category: "GST",
    simple: "GST on a sale that crosses states. It is one tax, not split into CGST and SGST.",
    advanced: "When the place of supply differs from the seller state, Kharcha credits IGST payable for the full rate.",
    why: "The customer still pays tax on top of your price. That tax is not profit.",
    caution: "This is not a filing instruction.",
    aliases: ["igst", "other state", "interstate"],
  },
  {
    id: "itc",
    simpleName: "Input tax credit",
    accountingName: "Input tax credit",
    category: "GST",
    simple: "GST you pay on business purchases is tracked separately as input GST. Kharcha does not decide that it is eligible to claim.",
    advanced: "Posted purchase bills debit Input CGST, Input SGST, or Input IGST. That balance is not an operating expense and it is not automatically netted against GST payable. Eligibility depends on the tax situation.",
    why: "A credit that was not recorded should not be assumed.",
    caution: "Whether a purchase qualifies is a tax question. Kharcha does not decide it.",
    aliases: ["input tax credit", "itc", "gst on purchases"],
  },
  {
    id: "pnl",
    simpleName: "Profit and loss",
    accountingName: "Profit & loss",
    category: "Accounting",
    simple: "A period report: what you earned minus what it cost. It answers whether the business made money.",
    advanced: "Rows run from revenue, to cost of sales, gross profit, operating expenses, EBITDA, then depreciation, interest, tax, and net profit.",
    why: "It is about a stretch of time, not the cash you hold today.",
    aliases: ["p&l", "profit and loss", "income statement"],
  },
  {
    id: "balance-sheet",
    simpleName: "Balance sheet",
    accountingName: "Balance sheet",
    category: "Accounting",
    simple: "A snapshot of what the business owns, what it owes, and what is left for the owners.",
    advanced: "Assets = liabilities + equity, including the period's earnings so the sheet stays in balance.",
    why: "It answers a different question from profit: what is the position right now.",
    aliases: ["balance sheet", "owns and owes"],
  },
  {
    id: "trial-balance",
    simpleName: "Trial balance",
    accountingName: "Trial balance",
    category: "Accounting",
    simple: "A check that every debit has a matching credit. If it fails, the books are not ready to trust.",
    advanced: "Kharcha refuses to post a journal whose debits and credits differ. The trial totals are a backstop, not a beginner metric.",
    why: "A report built on an unbalanced book would be wrong.",
    aliases: ["trial balance", "debits and credits"],
  },
  {
    id: "share",
    simpleName: "Shares",
    accountingName: "Shares",
    category: "Company Ownership",
    simple: "Units of ownership. More shares mean a larger claim, not a larger bank balance by themselves.",
    advanced: "Ownership percent is shares held divided by shares outstanding. Kharcha stores shares, not a hand-typed percent.",
    why: "A percent typed once goes stale the moment new shares exist.",
    aliases: ["share", "stock", "ownership percent"],
  },
  {
    id: "shareholder",
    simpleName: "Shareholder",
    accountingName: "Shareholder",
    category: "Company Ownership",
    simple: "A person or company that holds shares. They may or may not have a login to Kharcha.",
    advanced: "Cap-table holders are ownership. Team members are access. The two lists are separate.",
    why: "Giving an accountant a login does not give them the company.",
    aliases: ["shareholder", "founder", "investor"],
  },
  {
    id: "dilution",
    simpleName: "Dilution",
    accountingName: "Dilution",
    category: "Company Ownership",
    simple: "Your percentage can shrink when new shares are created, even if you keep every share you already had.",
    advanced: "A new issue increases shares outstanding. Existing holders' counts stay the same, so their percent falls. A transfer of existing shares does not do this by itself.",
    why: "Founders often think they lost shares when they only lost percent.",
    aliases: ["dilution", "percentage dropped"],
  },
  {
    id: "valuation",
    simpleName: "Valuation",
    accountingName: "Valuation",
    category: "Company Ownership",
    simple: "An agreed or estimated price for the company. It is not revenue, profit, or cash in the bank.",
    advanced: "Pre-money is the value before new investment. Post-money is pre-money plus the new investment. Investor percent is investment divided by post-money, when that is the deal.",
    why: "A high valuation does not mean the bank account grew.",
    caution: "Kharcha does not invent a valuation. If none is recorded, none is shown as yours.",
    aliases: ["company worth", "worth", "pre-money", "post-money", "valuation"],
  },
  {
    id: "pre-money",
    simpleName: "Pre-money",
    accountingName: "Pre-money valuation",
    category: "Company Ownership",
    simple: "What the company is valued at before a new investor's money is added.",
    advanced: "Post-money = pre-money + investment, in a simple priced round. Kharcha only shows this if you type a scenario. It is not saved as a fact.",
    why: "The price of the round and the cash in the bank are different numbers.",
    aliases: ["pre money", "before investment"],
  },
  {
    id: "post-money",
    simpleName: "Post-money",
    accountingName: "Post-money valuation",
    category: "Company Ownership",
    simple: "The pre-money value plus the new investment.",
    advanced: "Investor ownership in a simple priced round is investment ÷ post-money. This is a scenario, not a recorded valuation, unless you have entered one.",
    why: "It explains the percent an investor would receive. It does not change your books by being viewed.",
    aliases: ["post money", "after investment"],
  },
  {
    id: "runway",
    simpleName: "Runway",
    accountingName: "Cash runway",
    category: "Money & Profit",
    simple: "How long current cash would last if spending stayed the same. Kharcha does not guess this unless both cash and a real spending rate exist.",
    advanced: "Runway is cash divided by the average monthly operating cash outflow of recent full months. If that average is not negative, Kharcha does not invent a runway.",
    why: "A single month of zero sales is not a burn rate.",
    aliases: ["runway", "how long will money last"],
  },
  {
    id: "api",
    simpleName: "API",
    accountingName: "API",
    category: "Developer",
    simple: "A way for another app to read or send only the business data you allow.",
    advanced: "Calls are authenticated with a key, limited by scopes, and writes can use an idempotency key so a retry does not post twice.",
    why: "A person login and an app login should not be the same thing.",
    aliases: ["api", "integration", "connect an app"],
  },
  {
    id: "api-key",
    simpleName: "API key",
    accountingName: "API key",
    category: "Developer",
    simple: "A password made for an app, with a short list of permissions. It is shown once. Learning pages never repeat it.",
    advanced: "Kharcha stores a hash of the secret, plus a prefix so you can recognize the key. Test and live keys are separate.",
    why: "A leaked full key is as serious as a password.",
    aliases: ["api key", "secret", "token"],
  },
  {
    id: "scopes",
    simpleName: "Permissions on a key",
    accountingName: "Scopes",
    category: "Developer",
    simple: "The list of actions that one key is allowed to take. A key cannot do something its scopes leave out.",
    advanced: "Scopes are not the same as a teammate's role. A person can be an accountant. A key can be limited to read invoices.",
    why: "An app should not receive the owner's full power by default.",
    aliases: ["scopes", "key permissions"],
  },
  {
    id: "idempotency",
    simpleName: "Safe retry",
    accountingName: "Idempotency",
    category: "Developer",
    simple: "If an app sends the same request twice, Kharcha can keep the second one from creating a second invoice or payment.",
    advanced: "The same idempotency key and the same body return the first result. The same key with a different body is a conflict.",
    why: "Networks retry. Books should not double-count because of that.",
    aliases: ["idempotency", "duplicate request", "retry"],
  },
  {
    id: "team-access",
    simpleName: "Team access",
    accountingName: "Membership",
    category: "Getting Started",
    simple: "A login to this business. It is not ownership and it does not split personal expenses.",
    advanced: "Roles are owner, admin, accountant, member, and viewer. Shares live on the cap table. Inviting an accountant does not issue shares.",
    why: "People confuse 'can open the books' with 'owns the company'.",
    aliases: ["team", "invite", "accountant access"],
  },
  {
    id: "vendor",
    simpleName: "Vendor",
    accountingName: "Vendor",
    category: "Expenses",
    simple: "A person or company your business pays. The name is a label. The record is the id.",
    advanced: "Vendors are not customers and they are not team members. Bills and payments point at the vendor id.",
    why: "You need to know who is owed, not just which category was used.",
    aliases: ["supplier", "who do i pay", "aws"],
  },
  {
    id: "bill",
    simpleName: "Bill",
    accountingName: "Accounts payable",
    category: "Expenses",
    simple: "A vendor has charged you and you may not have paid yet. A draft does not change the books.",
    advanced: "Posting debits the expense and input GST, and credits accounts payable. Paying later debits payable and credits the bank. The expense is not posted again.",
    why: "Paying immediately and promising to pay later are different.",
    aliases: ["bill", "pay later", "money to pay", "accounts payable"],
  },
  {
    id: "input-gst",
    simpleName: "Input GST tracked",
    accountingName: "Input GST",
    category: "GST",
    simple: "GST on a purchase is stored on its own. That does not mean it is a guaranteed tax credit.",
    advanced: "Same-state purchases split into Input CGST and Input SGST. Interstate purchases use Input IGST. The UI says tracked, not eligible.",
    why: "Mixing purchase tax into the expense would hide it, and calling it a credit would overclaim.",
    caution: "Tracking is not a claim that the GST is eligible.",
    aliases: ["input gst", "purchase gst"],
  },
  {
    id: "budget",
    simpleName: "Budget",
    accountingName: "Budget",
    category: "Money & Profit",
    simple: "A plan for what you expect to spend or earn. It does not change the books.",
    advanced: "Actual comes from posted journals. Variance is actual minus budget. Over budget is an actual that is higher than the plan.",
    why: "A plan and a result answer different questions.",
    aliases: ["budget", "variance", "over budget", "plan"],
  },
  {
    id: "loan",
    simpleName: "Loan",
    accountingName: "Loan payable",
    category: "Accounting",
    simple: "Money the business borrowed. Receiving it increases cash and what you owe. It is not revenue.",
    advanced: "Receipt debits bank and credits loans payable. A repayment splits principal, which reduces the loan, from interest, which is an expense.",
    why: "Treating the whole repayment as an expense overstates the cost and understates the remaining loan.",
    aliases: ["loan", "principal", "borrowed"],
  },
  {
    id: "fixed-asset",
    simpleName: "Fixed asset",
    accountingName: "Fixed asset",
    category: "Accounting",
    simple: "Something the business buys to use for a long time, like a laptop. The full price is not always an expense on day one.",
    advanced: "Purchase debits equipment and credits bank or payable. Depreciation later debits depreciation expense and credits accumulated depreciation. Ordinary purchases stay expenses unless you choose asset.",
    why: "Expensing a laptop immediately makes that month look worse than the use of the machine.",
    aliases: ["laptop", "asset", "depreciation", "fixed asset"],
  },
  {
    id: "burn",
    simpleName: "Burn rate",
    accountingName: "Operating cash outflow",
    category: "Money & Profit",
    simple: "How fast operating cash is leaving, averaged over recent full months. Ordinary expenses alone are not called burn.",
    advanced: "Kharcha averages monthly operating cash flow from the cash-flow classification. If that average is not negative, burn and runway are not estimated.",
    why: "A profit figure is not the cash leaving the bank.",
    aliases: ["burn rate", "runway", "how long will money last"],
  },
];

export const PAGE_LEARN: Record<string, { title: string; concepts: string[] }> = {
  home: { title: "What do these business numbers mean?", concepts: ["cash", "capital", "revenue", "profit", "receivable", "paid-personally", "retained"] },
  invoices: { title: "How invoices and payments work", concepts: ["invoice", "receivable", "gst", "credit-note", "cash"] },
  expenses: { title: "How business expenses affect profit and cash", concepts: ["expense", "paid-personally", "reimbursement", "bill", "vendor", "payable"] },
  reimbursements: { title: "Money the business owes the team", concepts: ["paid-personally", "reimbursement", "retained", "team-access"] },
  reports: { title: "How your business makes or loses money", concepts: ["pnl", "gross-profit", "ebitda", "net-profit", "balance-sheet", "cash-flow", "retained", "budget"] },
  equity: { title: "Who owns your company", concepts: ["share", "shareholder", "dilution", "valuation", "team-access"] },
  team: { title: "Access is not ownership", concepts: ["team-access", "shareholder", "share"] },
  developer: { title: "How another app can securely connect", concepts: ["api", "api-key", "scopes", "idempotency"] },
  guide: { title: "Kharcha Business Guide", concepts: LEARN_CONCEPTS.map((concept) => concept.id) },
};

export function conceptById(id: string) {
  return LEARN_CONCEPTS.find((concept) => concept.id === id) ?? null;
}

export function searchConcepts(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return LEARN_CONCEPTS;
  return LEARN_CONCEPTS.filter((concept) => {
    const hay = [concept.simpleName, concept.accountingName, concept.simple, concept.category, ...concept.aliases]
      .join(" ")
      .toLowerCase();
    return hay.includes(q) || concept.aliases.some((alias) => alias.includes(q) || q.includes(alias));
  });
}
